# Generated by Django 3.2.19 on 2023-05-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vyvojar',
            options={'ordering': ['jmenoVyvojare'], 'verbose_name': 'Vývojář', 'verbose_name_plural': 'Vývojáři'},
        ),
        migrations.AlterField(
            model_name='hra',
            name='datumVydani',
            field=models.DateField(help_text='Zadejte datum vydání hry', verbose_name='Datum vydání hry'),
        ),
    ]
