# Generated by Django 3.2.19 on 2023-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20230509_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hra',
            name='cena',
            field=models.PositiveIntegerField(help_text='Zadejte cenu hry', verbose_name='Cena hry'),
        ),
    ]
