# Generated by Django 3.2.19 on 2023-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20230509_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='popisek',
            field=models.TextField(blank=True, help_text='Zadejte popisek hry', null=True, verbose_name='Popisek hry'),
        ),
        migrations.AddField(
            model_name='vyvojar',
            name='pocetVydanychHer',
            field=models.PositiveBigIntegerField(default=0, help_text='Zadejte počet vydaných her', verbose_name='Počet vydaných her'),
        ),
        migrations.AddField(
            model_name='vyvojar',
            name='web',
            field=models.CharField(blank=True, help_text='Zadejte odkaz na webovou stránku vývojáře', max_length=250, null=True, unique=True, verbose_name='Webová stránka vývojáře'),
        ),
        migrations.AlterField(
            model_name='hrahaskategorie',
            name='hra',
            field=models.ManyToManyField(blank=True, to='games.Hra', verbose_name='Hra'),
        ),
        migrations.AlterField(
            model_name='hrahaskategorie',
            name='kategorie',
            field=models.ManyToManyField(blank=True, to='games.Kategorie', verbose_name='Kategorie'),
        ),
    ]
