# Generated by Django 3.2.19 on 2023-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20230509_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='kategorie',
            field=models.ManyToManyField(blank=True, to='games.Kategorie', verbose_name='Kategorie'),
        ),
        migrations.DeleteModel(
            name='HraHasKategorie',
        ),
    ]
